baseURL = "https://blog.samuelmaddock.com/"
languageCode = "en-us"
title = "Samuel Maddock’s Blog"
theme = "ananke"
enableRobotsTXT = true

[params]
  gitRepo = "https://github.com/samuelmaddock/blog.samuelmaddock.com"
  github = "https://github.com/samuelmaddock"
  twitter = "https://twitter.com/SamuelMaddock"
  custom_css = ["css/figure.css"]